name: Deploy API to Azure

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Match your .NET version

      - name: Restore dependencies
        run: dotnet restore ./APIProjectDirectory

      - name: Build and Publish API
        run: dotnet publish ./APIProjectDirectory -c Release -o api-publish

      - name: Deploy API to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "PayperworkAI-API"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: api-publish
