name: Build and deploy ASP.Net Core app to Azure Web App - PayperworkAI-API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'  # Use the correct version of .NET

      - name: Build with dotnet
        run: dotnet build MyRazorApp/Website.API/MyRazorApp.API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish MyRazorApp/Website.API/MyRazorApp.API.csproj -c Release -o ./MyRazorApp/Website.API/publish_output_api  # Updated output directory

      - name: List contents of the publish folder (Debugging)
        run: ls -R ./MyRazorApp/Website.API/publish_output_api  # Ensure the necessary files are present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./MyRazorApp/Website.API/publish_output_api  # Correct the path for the artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List downloaded artifact contents (Debugging)
        run: ls -R ./MyRazorApp/Website.API/publish_output_api  # Ensure the files are downloaded correctly

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E76ACC7F92F24E3AB689678895015E87 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E0D1C660A36E4077BD0643860431451F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E986EB7A3DE54692ABEDB55042AA3A6C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PayperworkAI-API'
          slot-name: 'Production'
          package: './MyRazorApp/Website.API/publish_output_api'  # Ensure this is the correct directory to deploy
